#include"functions.h"



void encrypt(Content*ct){
    //takes a content object pointer and perfoms an encryption using the key.

    FILE *source=NULL;
    FILE *target=NULL;
    char ch;
    char code_char;

    source = fopen(ct->source, "r");
    if (source == NULL) {
      printf("Appuyez sur une touche pour sortir...\n");
      exit(EXIT_FAILURE);
    }
    target = fopen("dest.crt", "w");
    //opens dest.crt files and create it if it doesnt exist, and overrides the content.

    if (target == NULL) {
      fclose(source);
      printf("Appuyez sur une touche pour sortir...\n");
      exit(EXIT_FAILURE);
    }

    int i =0;//counter that will allow to loop over the key.
    int keylen =strlen(ct->key);

    printf("fichier crypte : \n");
    while ((ch = fgetc(source)) != EOF){
    
        code_char=(ch-(ct->key[i%keylen]));
        //the code char is generated by substracting the ith element of the key.
        // loops over the key indexes and goes back to 0 when i is equal to keylen.

        fprintf(target, "%c",code_char);
        i++;
        
    }
    printf("votre fichier a bien ete crypte.\n");

    fclose(source);
    fclose(target);
    //remove_file(ct->source);
    //removes the source file after the encryption
    
};

void decrypt(Content*ct){
    //takes a content object pointer and perfoms a decryption using the key.
    FILE *source=NULL;
    FILE *target=NULL;
    char ch;
    char decoded_char;

    source = fopen(ct->source, "r");
    if (source == NULL) {
      printf("Appuyez sur une touche pour sortir...\n");
      exit(EXIT_FAILURE);
    }
    target = fopen("source.txt", "w");
    //saves the decrypted code in  source.txt

    if (target == NULL) {
      fclose(source);
      printf("Appuyez sur une touche pour sortir...\n");
      exit(EXIT_FAILURE);
    }

    int i =0;
    int keylen =strlen(ct->key);
    fseek(source, 0L, SEEK_END);//seek to the end of the file;
    int sz = ftell(source);//get the current position of the cursor

    // printf("the file size is %d \n",sz);
    rewind(source);//seek to the beginning 

    printf("fichier en clair : \n\n");
    //when decrypting we need to know the file size, if some characters are encrypted to -1 whick is the EOF.

    while ((ftell(source)!=sz)){
        ch = fgetc(source); 
        decoded_char=(ch+(ct->key[i%keylen]));

        printf("%c",decoded_char);
        fprintf(target, "%c",decoded_char);
        i++;
         
    }
    fclose(source);
    fclose(target);
    
};

//this is for flushing
int flush_input(FILE *fp) {
    int c;
    while ((c = getc(fp)) != EOF && c != '\n')
        continue;
    return c;
}

void create_perroc(char* key){
    FILE *perroc=NULL;
    perroc=fopen("perroc.def", "w");
    fprintf(perroc,"%s",key);
    fclose(perroc);

}
int is_key(char *key){
    FILE *perroc=NULL;
    char ch;
    int i =0;
    perroc=fopen("perroc.def", "r");
     if (perroc == NULL) {
      printf("Appuyez sur une touche pour sortir...\n");
      exit(EXIT_FAILURE);
    }

    char key2[20];
    while((ch=fgetc(perroc))!= EOF){
        key2[i]=ch;
        i++;
    }

    int lenk1=strlen(key);
    int lenk2=i;
    
    if (lenk1!=lenk2){
        return 0;
    }

    int cmp=1;
    for (int j=0;j<lenk1;j++){
        if(key[j]!=key2[j]){
            cmp=0;
        }
    }
    if(cmp==1){
        return 1;
    }else{
        return 0;
    }

}

void remove_file(char *filename){
   if (remove(filename) == 0) {
        printf("Le fichier source a ete supprime \n");
    } else {
        printf("Le fichier source n a pas ete supprime. \n");
    }

}